diffpy/diffpy.labpdfproc

src/diffpy/labpdfproc/functions.py
src/diffpy/labpdfproc/tests/test_functions.py

Tests passed assertion. Checked distances for both odd and even grid points (i.e., points on the circle, in the center, and at each quadrant) and for acute, right, and obtuse angles.

Tests for setting distances for each grid point

---

src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tests/test_tools.py
src/diffpy/labpdfproc/tools.py
src/diffpy/labpdfproc/user_functions.py

Initial commit for overloading wavelength
Code does the following: first set wavelength to default as anode-type Mo, if args.wavelength is provided then set it to args.wavelength, otherwise if anode-type is provided set it to that.
I can wrap this up into a function if we prefer that

closes #25: overload wavelength

---

src/diffpy/labpdfproc/tests/test_tools.py
src/diffpy/labpdfproc/tools.py

We refer {*known_sources, } which gives the output ('Mo', ...), do we prefer ['Mo', ...] or do we not have a preference about this?

closes #25: update wavelength function

---

src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tests/test_tools.py
src/diffpy/labpdfproc/tools.py

- Moved everything from previous branch, including adding -u argument, function for load_user_metadata, and basic tests.
- Edited help messgae, included docstring and more tests. Tested good cases (no inputs, put quotes around whitespace, no whitespaces before and after =, specify repeated keys, pairs with more than one = sign) and bad cases (do not put quotes around whitespace). I'm not sure if the inputs for test cases are intuitive enough. For example, if I specify `-u weather=rainy day=tuesday` or `-u "weather=rainy" "day=tuesday"`, then they are both interpreted as `["weather=rainy", "day=tuesday"]` when I print args.user_metadata. So this is what I put for inputs.

closes #26: loading user-specified key-value pairs

---

src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tests/test_tools.py
src/diffpy/labpdfproc/tools.py

- closes #23, #24.
- File list tests passed.
- For test case of "./input_dir", we also read the two file lists in the directory. In my current commit here I read the two file lists and append the data files in our input directories too. Please let me know if this is ideal.
- In tools.py: I added _parse_input_paths in addition to _parse_file_list_file and it returns a set of file paths for file list/single data file. list(set(input_paths)) removes the duplicates.

input file list

---

src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tests/conftest.py
src/diffpy/labpdfproc/tests/test_tools.py
src/diffpy/labpdfproc/tools.py

- Initial commit
- Related to Issue #52, examples are here #48
- I skipped file_list files as usual. Shall we allow the user to specify something like "file*"?

implement wildcard pattern for input

---

.github/workflows/testing.yml
requirements/requirements-dev.txt
src/diffpy/labpdfproc/functions.py
src/diffpy/labpdfproc/tests/test_functions.py

- closes #20
- Initial commit
- I have to add the line `n_points_on_diameter=N_POINTS_ON_DIAMETER` to make monkeypatch work in the test. It doesn't affect the current functionality but is probably not the desired behavior.. Any suggestions for this?

test for compute_cve()

---

src/diffpy/labpdfproc/functions.py
src/diffpy/labpdfproc/tests/test_functions.py

add private function for initating DO

---

src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tests/test_tools.py
src/diffpy/labpdfproc/tools.py

address comments about wavelength and anode type in #82

Check Anode type

---

src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tests/test_tools.py
src/diffpy/labpdfproc/tools.py

- closes #27
- initial commit
- Would it be helpful to make `_set_anode_type` (in tools.py) and `_preprocess_args` (in the test) as public functions?

load args into DO metadata

---

src/diffpy/labpdfproc/functions.py
src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tools.py

These were previously implemented in #87: corrected word spacing/typos and a defult value in main, and removed unused code.

minor fixes

---

README.rst

I'm adding back the background description and an example of running the app from the previous README.rst. They can be found in #84.

add back background description and an example of instruction in README.rst

---

news/xtype.rst
src/diffpy/labpdfproc/functions.py
src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tools.py
tests/test_functions.py
tests/test_tools.py

closes #45 
I implemented functions to allow corrections on grid other than tth. The edits include:
- In the main module, replace all "tth" with args.xtype.
- In the tools module, filter out invalid xtype or set args.xtype to "tth" or "q" based on inputs (this makes it easy to write the output files using the dump function).
- In compute_cve function in functions.py, interpolate cve_do we get from the global tth to the input grid.
Question: I didn't see functions that allow transfer between tth and d, so when xtype=d do we simply put xtype=tth?
@sbillinge ready for some feedback.

Implement xtype other than tth

---

.github/workflows/matrix-and-codecov-on-merge-to-main.yml
.github/workflows/tests-on-pr.yml

Python 3.11-3.13 matrix test now works.

Install `libgtk` for linux CI runner to build wxpython

---

news/gui.rst
requirements/conda.txt
requirements/pip.txt
src/diffpy/labpdfproc/labpdfprocapp.py

closes #57 
It's working for both CLI arguments and GUI. Here're some screenshots.
@sbillinge ready for some feedback!

add gooey support

---

.github/workflows/matrix-and-codecov-on-merge-to-main.yml
.github/workflows/tests-on-pr.yml
news/py313.rst
pyproject.toml

Closes https://github.com/diffpy/diffpy.labpdfproc/issues/138 - support py313 when `wxpython` supports py313
This issue was created 5 days ago... great timing.

Support Python 3.13 with wxPython 3.13 support on Conda-forge

---

news/muD.rst
src/diffpy/labpdfproc/mud_calculator.py
tests/test_mud_calculator.py

closes #122 
@sbillinge ready for review. This PR is just some small edit in functions and docstring.

finalize `mud_calculator.py`

---

news/muD2.rst
src/diffpy/labpdfproc/mud_calculator.py
tests/test_mud_calculator.py

addressed comments in #146
@bobleesj let me know if this title is more informative!

rename x to dz in `mud_calculator.py` and decrease error tolerance for tests

---

news/docstring-tests.rst
src/diffpy/labpdfproc/functions.py
src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tools.py
tests/test_functions.py
tests/test_tools.py

closes #150, closes #152
- Update docstrings and tests
- Add orcid argument in the main module and `load_user_info`

feat: Update docstrings and tests, introduce orcid argument

---

.codecov.yml
.flake8
.github/ISSUE_TEMPLATE/release_checklist.md
.github/workflows/build-wheel-release-upload.yml
.github/workflows/matrix-and-codecov-on-merge-to-main.yml
.github/workflows/publish-docs-on-release.yml
.gitignore
.isort.cfg
doc/source/conf.py
news/recut.rst
pyproject.toml
src/diffpy/labpdfproc/__init__.py
src/diffpy/labpdfproc/functions.py
src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tools.py
tests/conftest.py
tests/test_functions.py
tests/test_tools.py
tests/test_version.py

fix: re-cookiecut to follow new group standard

---

news/wavelength-workflow.rst
src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tools.py
tests/test_tools.py

closes #161
I will add functionality to load wavelength/anode type from config file in another PR after this is merged

feat: new wavelength workflow

---

README.rst
doc/source/examples/examples.rst
doc/source/examples/tools_example.rst
doc/source/utilities/tools_utility.rst
doc/source/utilities/utilities.rst
news/tools-doc.rst
src/diffpy/labpdfproc/tools.py

docs: for tools

---

news/muD-theoretical.rst
src/diffpy/labpdfproc/labpdfprocapp.py
src/diffpy/labpdfproc/tools.py
tests/test_tools.py

closes #143 
Here's a gui snapshot:

feat: options for estimating muD theoretically
